version: '2'
services:
  mongoshard1:
    container_name: mongoshard1
    hostname: mongoshard1
    image: mongo
    command: mongod --shardsvr --replSet mongoreplicaset1shard --dbpath /data/db --bind_ip_all --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    networks:
      - "mongobridge"
    volumes:
      - /mongodb/mongodb_shard/data1:/data/db
  mongoshard2:
    container_name: mongoshard2
    hostname: mongoshard2
    image: mongo
    command: mongod --shardsvr --replSet mongoreplicaset1shard --dbpath /data/db --bind_ip_all --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    networks:
      - "mongobridge"
    volumes:
      - /mongodb/mongodb_shard/data2:/data/db
  mongoshard3:
    container_name: mongoshard3
    hostname: mongoshard3
    image: mongo
    command: mongod --shardsvr --replSet mongoreplicaset1shard --dbpath /data/db --bind_ip_all --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    networks:
      - "mongobridge"
    volumes:
      - /mongodb/mongodb_shard/data3:/data/db
networks:
  mongobridge:
    driver: bridge

